buildpack: https://github.com/pkgr/heroku-buildpack-python#buildcurl
targets:
  ubuntu-14.04: true
  ubuntu-12.04: true
  debian-7: true
  debian-8: true
  centos-6: true
  centos-7: true
  sles-11: true
  sles-12: true
